version: "3"

includes:
  rust:
    taskfile: ./build-tools/taskfile.rust.yaml
    internal: true

tasks:
  clean:
    deps:
      - rust:clean.target
      - rust:clean.coverage

  test:
    - task: rust:test

  cover:
    - task: test
    - task: rust:coverage

  checks:
    - task: rust:checks

  compile:
    deps:
      - task: rust:compile
        vars:
          TARGET_TRIPLE: aarch64-unknown-linux-musl
          TARGET_PLATFORM: linux-arm64
      - task: rust:compile
        vars:
          TARGET_TRIPLE: x86_64-unknown-linux-musl
          TARGET_PLATFORM: linux-amd64
