name: build
env:
  RUST_VERSION: "1.70.0"
on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-lint-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup Rust
        run: |
          rustup install ${{ env.RUST_VERSION }}
          rustup component add clippy
      - name: Check lint
        run: |
          cargo clippy --no-deps
  fmt-check:
    name: Check formatting
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Rust
        run: |
          rustup install ${{ env.RUST_VERSION }}
          rustup component add rustfmt
      - name: Check formatting
        run: |
          cargo fmt --check
  compile:
    strategy:
      matrix:
        include:
          - output: linux-amd64
            target: x86_64-unknown-linux-musl
            config: X86_64_UNKNOWN_LINUX_MUSL
          - output: linux-arm64
            target: aarch64-unknown-linux-musl
            config: AARCH64_UNKNOWN_LINUX_MUSL
    name: Compile ${{ matrix.output }} binary
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup LLVM Caching
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: |
            ./llvm
          key: llvm-${{ runner.os }}
      - name: Setup LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Setup Rust Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ matrix.output }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup Rust
        run: |
          rustup install ${{ env.RUST_VERSION }}
      - name: Compile
        env:
          CARGO_TARGET_${{ matrix.config }}_LINKER: "./llvm/bin/lld"
        run: |
          make target/${{ matrix.output }}
      - name: Upload Targets
        uses: actions/upload-artifact@v3
        with:
          name: serveit-${{ matrix.output }}
          path: target/${{ matrix.output }}
  build-image:
    name: Build image
    needs:
      - lint
      - fmt-check
      - compile
    runs-on: ubuntu-22.04
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Setup Container Caching
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}
      - name: Download linux/amd64 binary
        uses: actions/download-artifact@v3
        with:
          name: serveit-linux-amd64
          path: target
      - name: Download linux/arm64 binary
        uses: actions/download-artifact@v3
        with:
          name: serveit-linux-arm64
          path: target
      - name: Build image
        run: make image-only DOCKER_CACHE=/tmp/.buildx-cache
