name: publish
env:
  RUST_VERSION: "1.70.0"
on:
  push:
    branches:
      - main

jobs:
  compile:
    strategy:
      matrix:
        include:
          - output: linux-amd64
            target: x86_64-unknown-linux-musl
            config: X86_64_UNKNOWN_LINUX_MUSL
          - output: linux-arm64
            target: aarch64-unknown-linux-musl
            config: AARCH64_UNKNOWN_LINUX_MUSL
    name: Compile ${{ matrix.output }} binary
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup LLVM Caching
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: |
            ./llvm
          key: llvm-${{ runner.os }}
      - name: Setup LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "15"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Setup Rust Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: cargo-${{ matrix.output }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Setup Rust
        run: |
          rustup install ${{ env.RUST_VERSION }}
      - name: Compile
        env:
          CARGO_TARGET_${{ matrix.config }}_LINKER: "./llvm/bin/lld"
        run: |
          make target/${{ matrix.output }}
      - name: Upload Targets
        uses: actions/upload-artifact@v3
        with:
          name: serveit-${{ matrix.output }}
          path: target/${{ matrix.output }}
  publish-image:
    name: Publish image
    env:
      CONTAINER_REGISTRY: ghcr.io
    needs:
      - compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: network=host
      - name: Signin to ${{ env.CONTAINER_REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Container Caching
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            buildx-${{ runner.os }}
      - name: Download linux/amd64 binary
        uses: actions/download-artifact@v3
        with:
          name: serveit-linux-amd64
          path: target
      - name: Download linux/arm64 binary
        uses: actions/download-artifact@v3
        with:
          name: serveit-linux-arm64
          path: target
      - name: Build image
        run: |
          make image-only \
            DOCKER_CACHE=/tmp/.buildx-cache \
            DOCKER_REGISTRY=${{ env.CONTAINER_REGISTRY }} \
            STAMP=${{ github.sha }}
